from setuptools import find_packages, setup

setup(
    name='StatOD',
    packages=find_packages(),
    version='0.1.0',
    description='Statistical Orbit Determination Package',
    author='John M',
    license='MIT',
    setup_requires=['pytest-runner', 
                    'sympy >= 1.9',
                    'numpy <= 1.22',
                    'scipy',
                    'sigfig',
                    'matplotlib',
                    'numba',
                    'joblib',
                    'tqdm',
                    'colorama',
                    'sphinx',
                    "sphinx_rtd_theme",
                    "sphinx-gallery"],
    install_requires=['pytest-runner', 
                    'sympy >= 1.9',
                    'numpy <= 1.22',
                    'scipy',
                    'sigfig',
                    'matplotlib',
                    'numba',
                    'joblib',
                    'tqdm',
                    'colorama',
                    'sphinx',
                    "sphinx_rtd_theme",
                    "sphinx-gallery"],
    tests_require=['pytest==4.4.1'],
    test_suite='tests',
)

